version: '3.8'
services:
  api:
    build: .
    image: parser_api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env.docker

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - testDB:/data/db

volumes:
  testDB: